"""add_word_analysis_cache

Revision ID: 644521425f9a
Revises: d2ec685ceb80
Create Date: 2026-05-13 23:25:52.535883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "644521425f9a"
down_revision: Union[str, Sequence[str], None] = "d2ec685ceb80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word_analysis_cache",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("word", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("word_normalized", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lemma", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("root", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("binyan", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "pos",
            sa.Enum(
                "VERB",
                "NOUN",
                "ADJECTIVE",
                "ADVERB",
                "PREPOSITION",
                "PRONOUN",
                "OTHER",
                name="partofspeech",
            ),
            nullable=False,
        ),
        sa.Column("gender", sa.Enum("MASCULINE", "FEMININE", name="gender"), nullable=True),
        sa.Column(
            "number", sa.Enum("SINGULAR", "PLURAL", "DUAL", name="grammaticalnumber"), nullable=True
        ),
        sa.Column("translation_ru", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("related_words", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lemma", "pos", name="uq_word_analysis_lemma_pos"),
    )
    op.drop_table("word_analysis")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word_analysis",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("word", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("context_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("lemma", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("root", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("binyan", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("translation", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "related_words",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("word_analysis_pkey")),
    )
    op.drop_table("word_analysis_cache")
    # ### end Alembic commands ###
