"""add_enums_generation

Revision ID: 9d26a04a0da7
Revises: 644521425f9a
Create Date: 2026-05-14 00:43:00.643009

"""

from os import name
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9d26a04a0da7"
down_revision: Union[str, Sequence[str], None] = "644521425f9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    binyan_enum = sa.Enum(
        "PAAL", "PIEL", "HIFIL", "HITPAEL", "NIFAL", "PUAL", "HUFAL", name="binyan"
    )
    binyan_enum.create(op.get_bind())
    op.alter_column(
        "word_analysis_cache",
        "binyan",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("PAAL", "PIEL", "HIFIL", "HITPAEL", "NIFAL", "PUAL", "HUFAL", name="binyan"),
        existing_nullable=True,
        postgresql_using="binyan::binyan",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "word_analysis_cache",
        "binyan",
        existing_type=sa.Enum(
            "PAAL", "PIEL", "HIFIL", "HITPAEL", "NIFAL", "PUAL", "HUFAL", name="binyan"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    sa.Enum(name="binyan").drop(op.get_bind())
    # ### end Alembic commands ###
