"""init

Revision ID: aae4cf02b2c3
Revises:
Create Date: 2026-05-09 01:26:16.153545

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "aae4cf02b2c3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.Enum("A1", "A2", "B1", name="level"), nullable=False),
        sa.Column("topics", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "word_analysis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("word", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("context_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lemma", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("root", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("binyan", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("translation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("related_words", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "learning_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("level", sa.Enum("A1", "A2", "B1", name="level"), nullable=False),
        sa.Column("generated_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_words", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_vocabulary",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("lemma", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status", sa.Enum("LEARNING", "KNOWN", "MASTERED", name="vocabstatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "card",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_vocab_id", sa.Uuid(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_review_at", sa.DateTime(), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_vocab_id"],
            ["user_vocabulary.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "card_review",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("example_sentence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["card.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("card_review")
    op.drop_table("card")
    op.drop_table("user_vocabulary")
    op.drop_table("learning_session")
    op.drop_table("word_analysis")
    op.drop_table("app_user")
    # ### end Alembic commands ###
