"""tighten nullable on json columns and add updated_at onupdate

Revision ID: d2ec685ceb80
Revises: b00e90813a7c
Create Date: 2026-05-09 19:31:26.783665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d2ec685ceb80"
down_revision: Union[str, Sequence[str], None] = "b00e90813a7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "app_user", "topics", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    op.alter_column(
        "learning_session",
        "target_words",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "word_analysis",
        "related_words",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "word_analysis",
        "related_words",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "learning_session",
        "target_words",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "app_user", "topics", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True
    )
    # ### end Alembic commands ###
